### ISSUE TITLE
Try setting a generously large COMPOSE_HTTP_TIMEOUT

### ISSUE THREAD

**Issue by jnm** [kobotoolbox/ansible#2]
It's a bummer to have the job fail because of
```
An HTTP request took too long to complete. Retry with --verbose to obtain debug information.An error has occurred
```
Maybe we can avoid it with a large `COMPOSE_HTTP_TIMEOUT`?

See https://chat.kobotoolbox.org/#narrow/stream/6-Support/topic/Production.20deployments/near/11453

**Comment by rroux** [comment]
I added ```COMPOSE_HTTP_TIMEOUT``` to the set of run.py commands to avoid timeouts.

On the other hand, the problem doesn't come from docker, but from the ```start_env.bash``` script.
It's launched when the instance starts. It automatically updates all the dockers thanks to the info in the instance tags.

```
@reboot / bin / bash /home/ubuntu/kobo-ec2/start_env.bash> /home/ubuntu/.start_env.log 2> & 1
```

I comment this line in the cron, everything works with ```Rundeck```.
(Strange, that I didn't get the error in my tests...)

Is it better to comment this line?
Or to run Rundeck from another AMI where the cron is commented? ```(AMI:kobo.hhi.frontend.ami.20201221a)```
